CREATE TABLE ind_lycees (
    id SERIAL PRIMARY KEY,
    etablissement VARCHAR(255),
    annee DATE NOT NULL,
    ville VARCHAR(100),
    uai VARCHAR(20) NOT NULL,
    departement VARCHAR(100),
    secteur VARCHAR(30),
    taux_de_reussite DECIMAL(5,1),
    taux_de_mentions DECIMAL(5,1),
    part_bacheliers_sortants_2de_1re_term DECIMAL(5,1),
    part_bacheliers_sortants_term DECIMAL(5,1),
    effectif_de_2de DECIMAL(5,1),
    effectif_de_1re DECIMAL(5,1),
    effectif_de_ter DECIMAL(5,1),
    taux_dacces_2nde_bac DECIMAL(5,1),
    taux_dacces_1re_bac DECIMAL(5,1),
    taux_dacces_term_bac DECIMAL(5,1),
    region VARCHAR(50),
    libelle_departement VARCHAR(100),
    VA_taux_de_reussite DECIMAL(5,1),
    VA_taux_dacces_2nde_bac DECIMAL(5,1),
    VA_du_taux_de_mentions DECIMAL(5,1),
    VA_du_taux_dacces_1re_bac DECIMAL(5,1),
    VA_du_taux_dacces_term_bac DECIMAL(5,1),
    nb_mentions_tb_avec_felicitations DECIMAL(5,1),
    nb_mentions_tb_sans_felicitations DECIMAL(5,1),
    nb_mentions_b DECIMAL(5,1),
    nb_mentions_ab DECIMAL(5,1)
);